[[inputs.icecast2]]

## Icecast2 Admin url
# url = "http://localhost:8000/admin/"

## Icecast2 Admin username
# username = "admin"

# Icecast2 Admin password
# password = "hackme"

## Maximum time to receive response
# response_timeout = "5s"

## Collect Listeners
# collect_listeners = true

## Path to MaxMind GeoLite2 or GeoIP2 city database
# geoip2_path = ""
